#### Compute principal components from ensembles of hector runs

library(assertthat)
library(foreach)

## Some ground rules on constructing principal components:
##
## When flattening a set of runs into a vector, the grouping order shall be
## experiment, variable, year.  That is, year will vary the most rapidly,
## experiment the least

compute_pc <- function(scenlist, experiments, variables, years, histyears)
{
    ## Drop the scenarios that we wont be using (this allows us to pass the same
    ## list every time)
    expts <- sapply(scenlist, function(d) {
                        expt <- unique(d$experiment)
                        assert_that(length(expt)==1)
                        expt
                    })
    scenlist <- scenlist[expts %in% experiments]
    assert_that(length(scenlist) == length(experiments)) # all the requested
                                        # experiments are represented.

    ## combine into a single dataset
    alldata <- dplyr::bind_rows(scenlist)

    ## Drop any variables and years we will not be using
    ishist <- grepl('[Hh]istorical', alldata$experiment)
    alldata <- dplyr::filter(alldata, variable %in% variables,
                             (ishist & year %in% histyears) | (!ishist & year %in% years))

    ## Check that all the requested variables and years are present for all
    ## experiments.  Technically, we should group by runid too, but that will be
    ## really slow, so we take it as given that all the runs were generated by
    ## the same process and will therefore have the same years, variables, etc.
    varchk <- dplyr::group_by(alldata, experiment) %>%
      dplyr::summarise(complete=all(variables %in% variable))
    assert_that(all(varchk$complete))

    yrchk <- dplyr::group_by(alldata, experiment, variable) %>%
      dplyr::summarise(complete=all(years %in% year) | all(histyears %in% year))
    assert_that(all(yrchk$complete))

    ## Now arrange the data in the order described above and split by runid
    alldata <- dplyr::arrange(alldata, runid, experiment, variable, year)
    alldata_l <- split(alldata, alldata$runid)

    ## Produce a matrix of our output values.  Runs in rows, and data items in
    ## columns.
    data_matrix <- do.call(rbind,
                           lapply(alldata_l, function(d){d$value}))


    ## Add some column names.
    proto <- alldata_l[[1]]
    cnames <- paste(proto$experiment, proto$variable, proto$year, sep='.')
    colnames(data_matrix) <- cnames

    ## Perform the PCA
    pca <- prcomp(data_matrix, center=TRUE, scale.=TRUE, retx=FALSE)

    ## Add our metadata
    pca$meta_data <- list(year=sort(years),
                          histyear=sort(histyears),
                          variable=sort(variables),
                          experiment=sort(experiments),
                          scenario=sort(unique(alldata$scenario)))

    pca
}

outdir <- 'PCA-data'

### Get principal components for the concentration-driven runs.
conc_files <- list.files('PCA-data', '^concen-', full.names=TRUE)
conc_scenlist <- lapply(conc_files, readRDS)
conc_expts <- sapply(conc_scenlist, function(d){d$experiment[1]})
## We want to do all combinations of these scenarios.  There are 31 possible
## combinations (not counting the degenerate case where none of them are
## included).  Number them from 1-15 and use the bit patterns to figure out
## which scenarios should be included.
doParallel::registerDoParallel(cores=8)
conc_pcas <- foreach(i=1:31) %dopar%
{
    expts_l <- as.logical(c(bitwAnd(i,1), bitwAnd(i,2), bitwAnd(i,4), bitwAnd(i,8), bitwAnd(i,16)))
    expts <- conc_expts[expts_l]
    scenlist <- conc_scenlist[expts_l]

    compute_pc(scenlist, expts, 'tas', 2006:2100, 1861:2005)
}
for(pca in conc_pcas) {
    filename <- paste0('pc-conc-',paste0(pca$meta_data$experiment,
                                            collapse='-'), '.rds')
    saveRDS(pca, file.path(outdir, filename))
}


## For the emissions run we really only want the rcp85 and historical runs for now
emiss_files <- c('PCA-data/emissCC-esmrcp85.rds', 'PCA-data/emissCC-esmHistorical.rds')
emiss_scenlist <- lapply(emiss_files, readRDS)
emiss_pca <- compute_pc(emiss_scenlist, c('esmrcp85', 'esmHistorical'), c('tas','co2'), 2006:2100, 1861:2005)
saveRDS(emiss_pca, file.path(outdir, 'pc-emissCC-esmHistorical-esmrcp85.rds'))

