

#' Produce summary statistics for hector outputs
#'
#' For a matrix of samples of parameter values, produce summary statistics for
#' the hector outputs generated by those parameters
#'
#' @param params Matrix of parameter samples, parameters in columns, samples in
#' rows.
#' @param hcores A hector core, or a list of hector cores, configured for the
#' appropriate emissons.  If a list of cores is supplied, the samples will be
#' run in parallel
#' @param pnames Vector of hector parameter names corresponding to the columns
#' in the params array.
#' @param times Vector of times to sample.
#' @param nsamp Number of samples to take.  More samples gives more accuracy,
#' but takes longer.  Default is greater of 100 or 10% of the number of input
#' samples.
#' @param quantiles Quantiles to report
#' @return matrix of quantile values for each time and variable
#' importFrom foreach foreach %do% %dopar%
#' @export
hector_output_stats <- function(params, hcores, pnames,
                                times=c(2000, 2050, 2100), nsamp=NULL,
                                quantiles=c(0, 0.025, 0.25, 0.5, 0.75, 0.975, 1))
{
    nstot <- nrow(params)
    if(is.null(nsamp)) {
        nsamp <- min(max(100, 0.1*nstot), nstot)
    }

    samp_indices <- sample.int(nstot, nsamp)

    sampsmatrix <-
        if(is.list(hcores)) {
            ncore <- length(hcores)
            foreach(icore=seq(1,ncore), .combine=rbind) %dopar% {
                idx <- samp_indices[seq(icore, nsamp, ncore)]
                foreach(i=idx, .combine=rbind) %do% {
                    hos_helper(hcores[[icore]], params[i,], pnames, times)
                }
            }
        }
    else {
        foreach(i=idx, .combine=rbind) %do% {
            hos_helper(hcores, params[i,], pnames, times)
        }
    }

    ## samples matrix has samples in rows, vars in columns
    apply(sampsmatrix, 2, function(x){quantile(x, quantiles)})
}


## helper function for hector_output_stats
hos_helper <- function(hcore, params, pnames, times)
{
    for(i in seq_along(params)) {
        hector::setvar(hcore, NA, pnames[i], params[i], hector::getunits(pnames[i]))
    }

    hector::reset(hcore)
    hector::run(hcore, max(times))

    vars <- c(hector::GLOBAL_TEMP(), hector::ATMOSPHERIC_CO2())
    hdata <- hector::fetchvars(hcore, times, vars)

    v <- hdata$value
    names(v) <- interaction(hdata$variable, hdata$year)
    v
}
